
Cora_node:
  drop_rate1: 0.1
  drop_rate2: 0.3
  lambda: 2
  lr: 0.0007
  tau2: 0.5
  wd: 0.0004
  rb_order: 3
  epoch: 1600
Cora_link:
  drop_rate1: 0.2
  drop_rate2: 0.3
  lambda: 1
  lr: 0.0004
  tau2: 0.7
  wd: 0.0006
  rb_order: 3
  epoch: 2000
Cora_clu:
  drop_rate1: 0.2
  drop_rate2: 0.4
  lambda: 2
  lr: 0.0005
  tau2: 0.7
  wd: 0.0006
  rb_order: 3
  epoch: 1500